# Generated by Django 3.2.12 on 2022-11-28 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mes_crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbplan',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tbproductinout',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tbprogresshist',
            options={'managed': True},
        ),
    ]
